# @format

language: node_js
node_js:
  - node
notifications:
  slack:
    secure: TQWXGVeMUift8dsKs7oJR0GXT8gZAN6qzHDJsS4JMhfPcx/CiEhysAfwU6hJ4WVsljZjl5cnwlY96Elb/Z0d1GXv54zuZBdPamLKohe9pITi/MoxwRyuqUk2Jw9mYV0Y+0exJnV7Wi6fhkr2QQ8Zat6yHWq/Md6wvKscMXovVjXA41mFJnSevq6ZYWGeFRSv1wVZ1zQywMqzHfhNwemzLjEytjoXAtoVhWBZdiQ+pS3ZqTCTUi7JA4JzDffnuGRBncD2eWEEcDS+OXwydri3kIKaETsR51EdKFagVxIKKpQhj9sgpEPOtGs5r6K2c99DyRD9sfLldc6N21Ijg13kDaFILgn+mBZcIfQaMnGXSiKONlvntILU3vvJFb1cXHeeS9MUURjStM6S4+YI7csqCfjbxIUy41I9swj84ionrhp9OY9dDVsKUSWKCbMyU4erWOtGvxmmVVLYeEJG+CMXzTEE9KEJqk6ULbmlrwgrrDUnNGhvUTOmij9QqglcCxULowO1S4tzgHTFmxOOLAxdpTSVFR3HFK9b1ehP8LuRwHW8sphrG3aN/j0UIHrhRsf7w1MuTEOEqDtMvSBkhFrxNWzmstKOM7JS3SIWqgcVpj0zmsiOJV2PEezGDxRno56DcDIupsC0OCw6DiQUT/KbmQYaHXHfzyp3kX0E+t8JVpY=
install:
  - npm install

script:
  - npm test

# env:
#   global:
#     secure: DBDyCvoA0ELMdWR/JpR1q8gZ67FmfJRJOw1AGrp40EopQNL0kDXt7W06Kq7azxM43sAhpCEzId2R6KJYjLpUO/h3+ZjI8Yr5RmB9/2lMWo0pag6yzk0roeogAuWAXk9dxvVLFTbpdI/66algJhUIXZ45CJLPBZP3JCJX2y+9joaNQd6Pzpz2oyRjrCiP0zrtpsstbLN4vIae4Qm417EVq6S614Wt3k1f69B5Vw+BU4y1wc5SmVBN3hoTSGEXo3fng0NxQa1hUUMfkG/GJD9g9abW6d2n9H5XddgGJdjIfYB8yyWBy3YSnQwAAQesgdQKYWO/QajTE6j2BePsHH304rtxQXKUGbokHrRrww0I/C/EKfx+B/pe5JO/BWC1fff7XJY6Zt0yk/Bb+1I3n91PJHBE8yFzHd/a8VBnNfw41Dld0hvZVfzuttVSB6DaA4PqYEuozsM94vTMfXk2VD/Abcql9iVBVkr26PO7SkTb39492iuzb7IKtogeCG7BtKePm1GQBtkF0Xfna9I4KqminVuehL6QE+8PZUkNPKL8GSSRLN/n4Eng3V/5eHxlYmBD8X9JgvZpWKxTAXpXcY7tC/ysdodJoiQka9UbSkYL87j0DK6BpKL/QQY+FiuzcJLs8Up2ICFHsy+fe9pz0mNd8faSa2bx0WoIgrj0YyUKMWo=
# after_success: "BRANCH_TO_MERGE_INTO=master GITHUB_REPO=minimal1/gr2da ./travis-merge.sh"
